### ISSUE TITLE
alphaFocusHighlight patches appear to be broken against st master

### ISSUE THREAD

**Issue by cmpunches** [juliusHuelsmann/st#24]
```
[ bagira @ forge.silogroup.lan ] << ~/development/external/st >>

[- git apply patch/02_focus_alpha/st-alphaFocusHighlight-20200212-2b8333f.diff
patch/02_focus_alpha/st-alphaFocusHighlight-20200212-2b8333f.diff:269: trailing whitespace.
        for (i = 0; i < dc.collen; i++)
error: patch failed: x.c:1663
error: x.c: patch does not apply
error: patch failed: x.c:757
error: x.c: patch does not apply
error: patch failed: x.c:763
error: x.c: patch does not apply

```

**Comment by cmpunches** [comment]
also the links in the suckless docs for this get a bunch of 404's.  a little cleanup is needed here.

**Comment by cmpunches** [comment]
update:
x.c:1663 i was able to adjust to get an approximation of the changes.  the patch itself will need changed to reflect xw's ime object providing xic.

**Comment by cmpunches** [comment]
same for x.c:757

**Comment by cmpunches** [comment]
git diff after changes
[ticket.txt](https://github.com/juliusHuelsmann/st/files/4209345/ticket.txt)

**Comment by juliusHuelsmann** [comment]
Thanks for the notification! I think this is due to the changes performed on the master brach since commit `895e5b5` and I will create and upload a patch that can be applied to the current head of master. As for the links: I updated the files from which the webpage are generated to reflect the new location of the patches a few days ago, but updates to the page take some time as have to be approved.

**Comment by juliusHuelsmann** [comment]
[This patch](https://github.com/juliusHuelsmann/st/releases/download/patchesV3/st-alphaFocusHighlight-20200216-26cdfeb.diff) can be applied against the current commit on the master branch, and will become available on the st wiki.

**Comment by cmpunches** [comment]
#teamwork
