### ISSUE TITLE
Option to Change All of Highlight Coloring

### ISSUE THREAD

**Issue by 0x0D15** [juliusHuelsmann/st#27]
First off thanks for the fantastic st fork I couldn't use st without these features. However the only thing I cant find is an option to change the highlight color of the visual line/visual mode as it always seems to be the default white no matter what color option I change in config.h. The active row/column respect the color var but once I move them around in visual mode  they only leave behind white highlighting.

**Comment by juliusHuelsmann** [comment]
Thanks!

>  an option to change the highlight color of the visual line/visual mode as it always seems to be the default white 

By default, selected text is displayed 'Reversed' (ATTR_REVERSE), which swaps the foreground and background color. 
This has two main advantages: That way,  
1. selection remains distinguishable from  non-selection, while the original color structure persists.
2. The contrast between background and foreground remains unchanged.

Hence in your example, the background color of your terminal is most likely black, and the default text color white, hence it appears as if the selection is highlighted by making the background white. 

However, this option can't be configured with custom colors.

Due to the advantages of reversing the background and foreground colors, I will keep the highlighting of a selection as-is in the main version; providing that option would cause clutter. 

 In case you still want to set custom selection foreground and background colors, you can find a solution in [This commit](https://github.com/juliusHuelsmann/st/commit/422c108d2b8d3612d6d1bc3ee0fb512ba0c0035e). I introduce two new variables (selbg, selfg), which are the default colors for the selection in the config file. You only have to change those to refer to the color you'ld like to have for the selected text.


If you want to try that out, pull and rebuild 
[this branch](https://github.com/juliusHuelsmann/st/tree/differentSelectionColor) with an updated config.h.

If you want to merge the changes into your code base of st, you can "git cherry-pick" the commit referenced above. 


### On the different modes in VimBrowse
I think I put some ambiguous wording into the documentation of the different modes avaialble via the VimBrowse patch, therefore this brief clarification: 
1. In case you just want to move around in the buffer of the terminal, you can do so after entering 'normal mode' (by default Alt+c). 
2. V / v already selects text in order to yank it afterwards.

**Comment by 0x0D15** [comment]
Pulled the branch and and compiled with new settings, everything worked well. Thanks again for all of your work.
